"""Convert CreatorOS markdown docs → single professional Word doc.

Produces /app/docs/CreatorOS_Design_Docs.docx with:
  - Cover page
  - Table of contents (auto-generated by Word on open)
  - Numbered headings per source doc
  - Code blocks in monospace with grey background
  - Tables (converted from markdown pipe tables)
  - Bulleted / numbered lists
"""
from __future__ import annotations

import re
from pathlib import Path

from docx import Document
from docx.enum.style import WD_STYLE_TYPE
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.enum.text import WD_ALIGN_PARAGRAPH, WD_BREAK
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Cm, Pt, RGBColor

DOCS_DIR = Path("/app/docs")
OUT = DOCS_DIR / "CreatorOS_Design_Docs.docx"

FILES = [
    ("01_HLD.md",           "Part I — High-Level Design"),
    ("02_LLD.md",           "Part II — Low-Level Design"),
    ("03_USER_JOURNEY.md",  "Part III — End-to-End User Journey"),
    ("04_METRICS_AND_AB.md","Part IV — Evaluation Metrics & A/B Testing"),
]

BRAND_GOLD = RGBColor(0xC9, 0x94, 0x1D)
INK        = RGBColor(0x1A, 0x1A, 0x1A)
MUTE       = RGBColor(0x66, 0x66, 0x66)
CODE_BG    = "F2F2F2"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def add_page_break(doc):
    doc.add_paragraph().add_run().add_break(WD_BREAK.PAGE)


def shade_cell(cell, fill_hex):
    tcPr = cell._tc.get_or_add_tcPr()
    shd = OxmlElement("w:shd")
    shd.set(qn("w:val"), "clear")
    shd.set(qn("w:color"), "auto")
    shd.set(qn("w:fill"), fill_hex)
    tcPr.append(shd)


def set_cell_borders(cell, size=4, color="CCCCCC"):
    tc = cell._tc
    tcPr = tc.get_or_add_tcPr()
    tcBorders = OxmlElement("w:tcBorders")
    for edge in ("top", "left", "bottom", "right"):
        b = OxmlElement(f"w:{edge}")
        b.set(qn("w:val"), "single")
        b.set(qn("w:sz"), str(size))
        b.set(qn("w:space"), "0")
        b.set(qn("w:color"), color)
        tcBorders.append(b)
    tcPr.append(tcBorders)


def set_style_font(style, name="Calibri", size_pt=11, color=None, bold=False):
    style.font.name = name
    style.font.size = Pt(size_pt)
    if color is not None:
        style.font.color.rgb = color
    style.font.bold = bold


def init_styles(doc):
    styles = doc.styles
    for h in ("Heading 1", "Heading 2", "Heading 3", "Heading 4"):
        if h in styles:
            s = styles[h]
            s.font.color.rgb = INK
    styles["Heading 1"].font.size = Pt(20)
    styles["Heading 1"].font.color.rgb = BRAND_GOLD
    styles["Heading 2"].font.size = Pt(15)
    styles["Heading 3"].font.size = Pt(13)
    styles["Heading 4"].font.size = Pt(11.5)

    # Custom code style
    if "CodeBlock" not in styles:
        code = styles.add_style("CodeBlock", WD_STYLE_TYPE.PARAGRAPH)
        code.font.name = "Consolas"
        code.font.size = Pt(9)
        code.paragraph_format.space_before = Pt(4)
        code.paragraph_format.space_after = Pt(4)
        code.paragraph_format.left_indent = Cm(0.3)


def add_cover(doc):
    for _ in range(6):
        doc.add_paragraph()
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r = p.add_run("CreatorOS")
    r.bold = True
    r.font.size = Pt(46)
    r.font.color.rgb = BRAND_GOLD

    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r = p.add_run("Complete Engineering Design Documentation")
    r.font.size = Pt(18)
    r.font.color.rgb = INK

    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r = p.add_run("HLD · LLD · User Journeys · Evaluation Metrics · A/B Framework")
    r.italic = True
    r.font.size = Pt(11)
    r.font.color.rgb = MUTE

    for _ in range(8):
        doc.add_paragraph()

    for line in ("Version 1.0", "June 2026", "Owner: Engineering"):
        p = doc.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        r = p.add_run(line)
        r.font.size = Pt(10)
        r.font.color.rgb = MUTE

    add_page_break(doc)


def add_toc(doc):
    doc.add_heading("Table of Contents", level=1)
    p = doc.add_paragraph()
    r = p.add_run(
        "To populate this Table of Contents, right-click below and choose "
        "\"Update Field\" (or press F9). Word will list every heading with its page number."
    )
    r.italic = True
    r.font.color.rgb = MUTE
    r.font.size = Pt(10)

    p = doc.add_paragraph()
    run = p.add_run()
    fldChar_begin = OxmlElement("w:fldChar")
    fldChar_begin.set(qn("w:fldCharType"), "begin")

    instr = OxmlElement("w:instrText")
    instr.set(qn("xml:space"), "preserve")
    instr.text = 'TOC \\o "1-3" \\h \\z \\u'

    fldChar_sep = OxmlElement("w:fldChar")
    fldChar_sep.set(qn("w:fldCharType"), "separate")

    fldChar_end = OxmlElement("w:fldChar")
    fldChar_end.set(qn("w:fldCharType"), "end")

    run._r.append(fldChar_begin)
    run._r.append(instr)
    run._r.append(fldChar_sep)
    run._r.append(fldChar_end)

    add_page_break(doc)


# ---------------------------------------------------------------------------
# Markdown → docx converter (subset — handles headings, code blocks, tables,
# lists, and inline code/bold/italic).
# ---------------------------------------------------------------------------
INLINE_CODE = re.compile(r"`([^`]+?)`")
BOLD_RE     = re.compile(r"\*\*(.+?)\*\*")
ITALIC_RE   = re.compile(r"(?<!\*)\*(?!\*)([^*]+?)\*")

TOKEN_CODE_OPEN  = "\uE001"
TOKEN_CODE_CLOSE = "\uE002"
TOKEN_BOLD_OPEN  = "\uE003"
TOKEN_BOLD_CLOSE = "\uE004"
TOKEN_ITAL_OPEN  = "\uE005"
TOKEN_ITAL_CLOSE = "\uE006"


def _tokenize(text: str) -> str:
    text = INLINE_CODE.sub(lambda m: f"{TOKEN_CODE_OPEN}{m.group(1)}{TOKEN_CODE_CLOSE}", text)
    text = BOLD_RE.sub(lambda m: f"{TOKEN_BOLD_OPEN}{m.group(1)}{TOKEN_BOLD_CLOSE}", text)
    text = ITALIC_RE.sub(lambda m: f"{TOKEN_ITAL_OPEN}{m.group(1)}{TOKEN_ITAL_CLOSE}", text)
    return text


def _emit_inline(paragraph, text: str):
    """Append runs to `paragraph` respecting bold/italic/code tokens."""
    text = _tokenize(text)
    buf = ""
    state = {"bold": False, "italic": False, "code": False}

    def flush():
        nonlocal buf
        if not buf:
            return
        run = paragraph.add_run(buf)
        if state["bold"]:
            run.bold = True
        if state["italic"]:
            run.italic = True
        if state["code"]:
            run.font.name = "Consolas"
            run.font.size = Pt(9.5)
            run.font.color.rgb = RGBColor(0x8E, 0x22, 0x38)
        buf = ""

    for ch in text:
        if ch == TOKEN_CODE_OPEN:
            flush(); state["code"] = True
        elif ch == TOKEN_CODE_CLOSE:
            flush(); state["code"] = False
        elif ch == TOKEN_BOLD_OPEN:
            flush(); state["bold"] = True
        elif ch == TOKEN_BOLD_CLOSE:
            flush(); state["bold"] = False
        elif ch == TOKEN_ITAL_OPEN:
            flush(); state["italic"] = True
        elif ch == TOKEN_ITAL_CLOSE:
            flush(); state["italic"] = False
        else:
            buf += ch
    flush()


def add_table_from_md(doc, header_line: str, sep_line: str, body_lines: list[str]):
    headers = [h.strip() for h in header_line.strip("|").split("|")]
    rows = []
    for l in body_lines:
        rows.append([c.strip() for c in l.strip("|").split("|")])

    n_cols = len(headers)
    table = doc.add_table(rows=1 + len(rows), cols=n_cols)
    table.alignment = WD_TABLE_ALIGNMENT.LEFT
    try:
        table.style = "Light Grid Accent 1"
    except Exception:
        pass
    table.autofit = True

    # Header
    hdr_cells = table.rows[0].cells
    for i, h in enumerate(headers):
        cell = hdr_cells[i]
        cell.text = ""
        p = cell.paragraphs[0]
        r = p.add_run(h)
        r.bold = True
        r.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)
        r.font.size = Pt(10)
        shade_cell(cell, "1A1A1A")
        set_cell_borders(cell)

    # Rows
    for row_i, row in enumerate(rows, start=1):
        for i in range(n_cols):
            cell = table.rows[row_i].cells[i]
            cell.text = ""
            p = cell.paragraphs[0]
            _emit_inline(p, row[i] if i < len(row) else "")
            for r in p.runs:
                r.font.size = Pt(9.5)
            set_cell_borders(cell)
            if row_i % 2 == 0:
                shade_cell(cell, "F8F8F8")


def add_code_block(doc, lines: list[str], lang: str = ""):
    text = "\n".join(lines)
    p = doc.add_paragraph(style="CodeBlock")
    # Shade the paragraph background
    pPr = p._p.get_or_add_pPr()
    shd = OxmlElement("w:shd")
    shd.set(qn("w:val"), "clear")
    shd.set(qn("w:color"), "auto")
    shd.set(qn("w:fill"), CODE_BG)
    pPr.append(shd)
    run = p.add_run(text)
    run.font.name = "Consolas"
    run.font.size = Pt(9)


def convert_markdown(doc, md_text: str):
    lines = md_text.splitlines()
    i = 0
    while i < len(lines):
        raw = lines[i]
        line = raw.rstrip()

        # Fenced code block
        m = re.match(r"^```(\w*)\s*$", line)
        if m:
            lang = m.group(1)
            i += 1
            block = []
            while i < len(lines) and not re.match(r"^```\s*$", lines[i]):
                block.append(lines[i])
                i += 1
            add_code_block(doc, block, lang)
            i += 1
            continue

        # Table (needs a separator line right after header)
        if line.startswith("|") and i + 1 < len(lines) and re.match(r"^\|[\s\-:|]+\|\s*$", lines[i + 1]):
            header_line = line
            sep_line = lines[i + 1]
            body: list[str] = []
            j = i + 2
            while j < len(lines) and lines[j].startswith("|"):
                body.append(lines[j])
                j += 1
            add_table_from_md(doc, header_line, sep_line, body)
            i = j
            continue

        # Headings
        m = re.match(r"^(#{1,6})\s+(.*)$", line)
        if m:
            level = len(m.group(1))
            text = m.group(2).strip()
            # Map # → Heading 1, ## → Heading 2, etc. Cap at 4.
            h = doc.add_heading(level=min(4, level))
            _emit_inline(h, text)
            i += 1
            continue

        # Horizontal rule
        if re.match(r"^\s*---+\s*$", line):
            p = doc.add_paragraph()
            p.paragraph_format.space_after = Pt(0)
            pPr = p._p.get_or_add_pPr()
            pBdr = OxmlElement("w:pBdr")
            bot = OxmlElement("w:bottom")
            bot.set(qn("w:val"), "single")
            bot.set(qn("w:sz"), "6")
            bot.set(qn("w:space"), "1")
            bot.set(qn("w:color"), "CCCCCC")
            pBdr.append(bot)
            pPr.append(pBdr)
            i += 1
            continue

        # Numbered list
        m = re.match(r"^(\s*)(\d+)\.\s+(.*)$", line)
        if m:
            indent = len(m.group(1)) // 2
            p = doc.add_paragraph(style="List Number")
            p.paragraph_format.left_indent = Cm(0.5 + indent * 0.6)
            _emit_inline(p, m.group(3))
            i += 1
            continue

        # Bulleted list
        m = re.match(r"^(\s*)[-*]\s+(.*)$", line)
        if m:
            indent = len(m.group(1)) // 2
            p = doc.add_paragraph(style="List Bullet")
            p.paragraph_format.left_indent = Cm(0.5 + indent * 0.6)
            _emit_inline(p, m.group(2))
            i += 1
            continue

        # Blank line
        if line.strip() == "":
            doc.add_paragraph()
            i += 1
            continue

        # Normal paragraph
        p = doc.add_paragraph()
        _emit_inline(p, line)
        i += 1


def add_part_title(doc, title: str):
    for _ in range(4):
        doc.add_paragraph()
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r = p.add_run(title)
    r.bold = True
    r.font.size = Pt(28)
    r.font.color.rgb = BRAND_GOLD
    doc.add_paragraph()
    for _ in range(2):
        doc.add_paragraph()
    add_page_break(doc)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main():
    doc = Document()

    # Page setup — A4 with tighter margins
    for section in doc.sections:
        section.top_margin = Cm(2.0)
        section.bottom_margin = Cm(2.0)
        section.left_margin = Cm(2.0)
        section.right_margin = Cm(2.0)

    init_styles(doc)
    add_cover(doc)
    add_toc(doc)

    for filename, part_title in FILES:
        add_part_title(doc, part_title)
        md_path = DOCS_DIR / filename
        md_text = md_path.read_text(encoding="utf-8")
        convert_markdown(doc, md_text)
        add_page_break(doc)

    # Footer with brand mark
    section = doc.sections[0]
    footer_p = section.footer.paragraphs[0]
    footer_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r = footer_p.add_run("CreatorOS · Engineering Design Documentation · Confidential")
    r.font.size = Pt(8)
    r.font.color.rgb = MUTE

    doc.save(OUT)
    print(f"Wrote: {OUT}  ({OUT.stat().st_size / 1024:.1f} KB)")


if __name__ == "__main__":
    main()
